name: Build React App

on:
  push:
    branches:
      - main    # or your default branch
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      # Optionally, you can upload the build artifact for use in other jobs:
      - name: Upload build folder
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: build/
